export const FETCH_COMMENTS_REQUEST="FETCH_COMMENTS_REQUEST"
export const FETCH_COMMENTS_SUCCESS="FETCH_COMMENTS_SUCCESS"
export const FETCH_COMMENTS_FAILED="FETCH_COMMENTS_FAILED"



export const ADD_COMMENTS_REQUEST="ADD_COMMENTS_REQUEST"
export const ADD_COMMENTS_SUCCESS="ADD_COMMENTS_SUCCESS"
export const ADD_COMMENTS_FAILED="ADD_COMMENTS_FAILED"


export const FETCH_MORE_COMMENTS_REQUEST="FETCH_MORE_COMMENTS_REQUEST"
export const FETCH_MORE_COMMENTS_SUCCESS="FETCH_MORE_COMMENTS_SUCCESS"
export const FETCH_MORE_COMMENTS_FAILED="FETCH_MORE_COMMENTS_FAILED"


