export const GET_USER_DETAILS_REQUEST="GET_USER_DETAILS_REQUEST"
export const GET_USER_DETAILS_SUCCESS="GET_USER_DETAILS_SUCCESS"
export const GET_USER_DETAILS_FAILED="GET_USER_DETAILS_FAILED"


export const GET_USER_VIDEOS_REQUEST="GET_USER_VIDEOS_REQUEST"
export const GET_USER_VIDEOS_SUCCESS="GET_USER_VIDEOS_SUCCESS"
export const GET_USER_VIDEOS_FAILED="GET_USER_VIDEOS_FAILED"

export const GET_MORE_USER_VIDEOS_SUCCESS="GET_MORE_USER_VIDEOS_SUCCESS"
export const GET_MORE_USER_VIDEOS_FAILED="GET_MORE_USER_VIDEOS_FAILED"
export const GET_MORE_USER_VIDEOS_REQUEST="GET_MORE_USER_VIDEOS_REQUESR"

export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILED="LOGIN_FAILED"

export const SIGNUP_USER_REQUEST="SIGNUP_USER_REQUEST"
export const SIGNUP_USER_SUCCESS="SIGNUP_USER_SUCCESS"
export const SIGNUP_USER_FAILED="SIGNUP_USER_FAILED"

export const UPLOAD_VIDEO_REQUEST="UPLOAD_VIDEO_REQUEST"
export const UPLOAD_VIDEO_SUCCESS="UPLOAD_VIDEO_SUCCESS"
export const UPLOAD_VIDEO_FAILED="UPLOAD_VIDEO_FAILED"



export const LOG_OUT_REQUEST="LOG_OUT_REQUEST"
export const LOG_OUT_SUCCESS="LOG_OUT_SUCCESS"
export const LOG_OUT_FAILED="LOG_OUT_FAILED"

export const RESET_PASSWORD_LINK_REQUEST="RESET_PASSWORD_LINK_REQUEST"
export const RESET_PASSWORD_LINK_SUCCESS="RESET_PASSWORD_LINK_SUCCESS"
export const RESET_PASSWORD_LINK_FAILED="RESET_PASSWORD_LINK_FAILED"


