export const FETCH_VIDEO_Tags_REQUEST="FETCH_VIDEO_Tags_REQUEST"
export const FETCH_VIDEO_Tags_SUCCESS="FETCH_VIDEO_Tags_SUCCESS"
export const FETCH_VIDEO_Tags_FAILED="FETCH_VIDEO_Tags_FAILED"

export const FETCH_MORE_VIDEO_Tags_REQUEST="FETCH_MORE_VIDEO_Tags_REQUEST"
export const FETCH_MORE_VIDEO_Tags_SUCCESS="FETCH_MORE_VIDEO_Tags_SUCCESS"
export const FETCH_MORE_VIDEO_Tags_FAILED="FETCH_MORE_VIDEO_Tags_FAILED"







