

export const FETCH_VIDEOS_REQUEST="FETCH_VIDEOS_REQUEST"
export const FETCH_VIDEOS_SUCCESS="FETCH_VIDEOS_SUCCESS"
export const FETCH_VIDEOS_FAILED="FETCH_VIDEOS_FAILED"


export const FETCH_MORE_VIDEOS_REQUEST="FETCH_MORE_VIDEOS_REQUEST"
export const FETCH_MORE_VIDEOS_SUCCESS="FETCH_MORE_VIDEOS_SUCCESS"
export const FETCH_MORE_VIDEOS_FAILED="FETCH_MORE_VIDEOS_FAILED"

export const UPLOAD_VIDEO_REQUEST="UPLOAD_VIDEO_REQUEST"
export const UPLOAD_VIDEO_SUCCESS="UPLOAD_VIDEO_SUCCESS"
export const UPLOAD_VIDEO_FAILED="UPLOAD_VIDEO_FAILED"



